version: '3.9'

services:
  gnp:
    build:
      dockerfile: Dockerfile
    command: sh -c "/wait && ./gnp"
    ports:
      - "8080:8080"
    depends_on:
      - posgresdb
      - minio1
    environment:
      - DB_HOST=posgresdb
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_NAME=postgres
      - DB_SSLMODE=disable
      - DB_PASSWORD=postgres
      - WAIT_HOSTS=posgresdb:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
      - AUTH_SALT=yRu376r2g742gye67q3r76
      - AUTH_SECRET=we32r2t34

  posgresdb:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  minio1:
    restart: always
    image: quay.io/minio/minio    # :RELEASE.2022-10-05T14-58-27Z
    command: server /data --console-address ":9090"
    hostname: minio1

    environment:
      MINIO_ROOT_USER: ROOTUSER
      MINIO_ROOT_PASSWORD: CHANGEME123

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

    volumes:
      - ./.database/minio_data:/data

    ports:
      - "9000:9000"
      - "9090:9090"
